---
- hosts: localhost
  connection: local
  vars:
    minio_admin_user: "{{ admin_user | default('minioadmin') }}"
    minio_admin_pass: "{{ admin_pass | default('minioadmin') }}"
    minio_dns_console: "{{ dns_console }}"
    minio_dns_api: "{{ dns_api }}"
    minio_letsencrypt_email: "{{ letsencrypt_email }}"
    minio_release: "{{ release }}"
  roles:
  - role: 'grycap.docker'
  tasks:
  - name:
    file:
      path: /opt/minio
      state: directory
      mode: '0755'

  - name: Create docker-compose file
    copy:
      content: |
        version: "3.3"
        
        services:
          traefik:
            image: "traefik:v2.10"
            container_name: "traefik"
            command:
              # - "--log.level=DEBUG"
              - "--api.insecure=true"
              - "--providers.docker=true"
              - "--providers.docker.exposedbydefault=false"
              - "--entrypoints.web.address=:80"
              - "--entrypoints.websecure.address=:443"
              - "--entrypoints.web.http.redirections.entryPoint.to=websecure"
              - "--entrypoints.web.http.redirections.entryPoint.scheme=https"
              - "--entrypoints.web.http.redirections.entrypoint.permanent=true"
              - "--certificatesresolvers.myresolver.acme.httpchallenge=true"
              - "--certificatesresolvers.myresolver.acme.httpchallenge.entrypoint=web"
              #- "--certificatesresolvers.myresolver.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory"
              - "--certificatesresolvers.myresolver.acme.email={{ minio_letsencrypt_email  }}"
              - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
            ports:
              - "80:80"
              - "443:443"
              - "8080:8080"
            volumes:
              - "./letsencrypt:/letsencrypt"
              - "/var/run/docker.sock:/var/run/docker.sock:ro"
        
          minio:
            # taken from: https://github.com/minio/minio/tags
            image: quay.io/minio/minio:{{ minio_release }}
            volumes:
              - minio-data:/data
            command:
              - server
              - /data
              - --console-address
              - ":9001"
            environment:
              - MINIO_ROOT_USER={{ minio_admin_user }}
              - MINIO_ROOT_PASSWORD={{ minio_admin_pass }}
              - MINIO_SERVER_URL=https://{{ minio_dns_api }}
              - MINIO_BROWSER_REDIRECT_URL=https://{{ minio_dns_console }}
            labels:
              - "traefik.enable=true"
              - "traefik.http.routers.minio.service=minio"
              - "traefik.http.routers.minio.rule=Host(`{{ minio_dns_api }}`)"
              - "traefik.http.routers.minio.entrypoints=websecure"
              - "traefik.http.routers.minio.tls.certresolver=myresolver"
              - "traefik.http.services.minio.loadbalancer.server.port=9000"
              - "traefik.http.routers.minio-console.service=minio-console"
              - "traefik.http.routers.minio-console.rule=Host(`{{ minio_dns_console }}`)"
              - "traefik.http.routers.minio-console.entrypoints=websecure"
              - "traefik.http.routers.minio-console.tls.certresolver=myresolver"
              - "traefik.http.services.minio-console.loadbalancer.server.port=9001"
        
        volumes:
          minio-data:
      dest: /opt/minio/docker-compose.yaml

  - name: docker-compose up
    docker_compose:
      project_src: /opt/minio/
      state: present
