---
- hosts: localhost
  connection: local
  tasks:
  - name: Use curl to configure DNS hostname via https://nsupdate.fedcloud.eu/
    ansible.builtin.shell: curl https://{{ nsupdate_fqdn }}:{{ nsupdate_secret }}@nsupdate.fedcloud.eu/nic/update
